[package]
name = "ttyper"
description = "Terminal-based typing test."
version = "0.4.2"
readme = "README.md"
repository = "https://github.com/max-niederman/ttyper.git"
homepage = "https://github.com/max-niederman/ttyper"
license = "MIT"
authors = ["Max Niederman <max@maxniederman.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
dirs = "4.0"
crossterm = "0.23"
rust-embed = "6.2"
toml = "0.5"

[dependencies.tui]
version = "0.17"
default-features = false
features = ["crossterm"]

[dependencies.rand]
version = "0.8"
features = ["alloc"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[build-dependencies]
dirs = "4.0"
